export let industries: any = [
  { id: "1", title: "Utilities installation" },
  { id: "2", title: "Building finishing contractors" },
  { id: "3", title: "Construction equipment contractors" },
  { id: "4", title: "Building contractors" },
  { id: "5", title: "Specialty trade contractors" },
  { id: "6", title: "Natural gas distribution" },
  { id: "7", title: "Natural gas extraction" },
  { id: "8", title: "Accommodation services" },
  { id: "9", title: "Justice administration" },
  { id: "10", title: "Government administration" },
  { id: "11", title: "Education administration programs" },
  { id: "12", title: "Administrative and support services" },
  { id: "13", title: "Legal services" },
  { id: "14", title: "Waste collection" },
  { id: "15", title: "Waste treatment and disposal" },
  { id: "16", title: "Alternative medicine" },
  { id: "17", title: "Ambulance services" },
  { id: "18", title: "Animation & post-production" },
  { id: "19", title: "Architecture & urban planning" },
  { id: "20", title: "Physicians" },
  { id: "21", title: "Banking" },
  { id: "22", title: "Bars, cafes, and nightclubs" },
  { id: "23", title: "Primary and secondary education" },
  { id: "24", title: "Bed and breakfasts, hostels, homestays" },
  { id: "25", title: "Business consulting and services" },
  { id: "26", title: "Corporate content" },
  { id: "27", title: "Investment advice" },
  { id: "28", title: "Vocational rehabilitation" },
  { id: "29", title: "Fire protection" },
  { id: "30", title: "Security and investigation services" },
  { id: "31", title: "Security services and patrol services" },
  { id: "32", title: "Libraries" },
  { id: "33", title: "Biotechnological research" },
  { id: "34", title: "Blockchain services" },
  { id: "35", title: "Blogs" },
  { id: "36", title: "Forestry and logging" },
  { id: "37", title: "Construction" },
  { id: "38", title: "Building construction" },
  { id: "39", title: "Breweries" },
  { id: "40", title: "Business intelligence platforms" },
  { id: "41", title: "Catering" },
  { id: "42", title: "Family planning centers" },
  { id: "43", title: "Chemical and agricultural production" },
  { id: "44", title: "Chemical manufacturing" },
  { id: "45", title: "Chiropractors" },
  { id: "46", title: "Circuses and magic shows" },
  { id: "47", title: "Civil and social organizations" },
  { id: "48", title: "Civil engineering" },
  { id: "49", title: "Computer and network security" },
  { id: "50", title: "Computer games" },
  { id: "51", title: "Conflict resolution" },
  { id: "52", title: "Consulting outsourcing and offshoring" },
  { id: "53", title: "Cosmetology and barber schools" },
  { id: "54", title: "Dance companies" },
  { id: "55", title: "Think tanks" },
  { id: "56", title: "Design services" },
  { id: "57", title: "Retail" },
  { id: "58", title: "Gasoline stations" },
  { id: "59", title: "Book and magazine retail" },
  { id: "60", title: "Building material and garden equipment retail" },
  { id: "61", title: "Creative tools retail" },
  { id: "62", title: "Health and personal care product retail" },
  { id: "63", title: "Household appliance and consumer electronics retail" },
  { id: "64", title: "Office supplies and gift retail" },
  { id: "65", title: "Clothing and fashion retail" },
  { id: "66", title: "Grocery retail" },
  { id: "67", title: "Food and beverage retail" },
  { id: "68", title: "Luxury goods and jewelry retail" },
  { id: "69", title: "Furniture and interior retail" },
  { id: "70", title: "Motor vehicle retail" },
  { id: "71", title: "Musical instrument retail" },
  { id: "72", title: "Online and mail-order retail" },
  { id: "73", title: "Recyclable materials and second-hand items retail" },
  { id: "74", title: "Security systems services" },
  { id: "75", title: "Veterinary services" },
  { id: "76", title: "Government relations services" },
  { id: "77", title: "Human resources services" },
  { id: "78", title: "Personal care services" },
  { id: "79", title: "Landscaping services" },
  { id: "80", title: "Senior and disabled services" },
  {
    id: "81",
    title:
      "Water supply, waste management, steam and air conditioning services",
  },
  { id: "82", title: "Zoos and botanical gardens" },
  { id: "83", title: "Animal feed production" },
  { id: "84", title: "Animal care" },
  { id: "85", title: "Private equity and venture capital" },
  { id: "86", title: "Distilleries" },
  { id: "87", title: "Wireless services" },
  { id: "88", title: "Printing companies" },
  { id: "89", title: "Economic programs" },
  { id: "90", title: "Securities and commodities exchanges" },
  { id: "91", title: "E-learning training" },
  { id: "92", title: "Electricity transmission, control, and distribution" },
  { id: "93", title: "Electric power generation" },
  { id: "94", title: "Embedded software products" },
  { id: "95", title: "Renewable energy generation" },
  { id: "96", title: "Entertainment providers" },
  { id: "97", title: "Ergonomists, physiotherapists, and speech therapists" },
  { id: "98", title: "Event services" },
  { id: "99", title: "Facility services" },
  { id: "100", title: "Pharmaceutical manufacturing" },
  { id: "101", title: "Philanthropic fundraising services" },
  { id: "102", title: "Film and sound recording" },
  { id: "103", title: "Films, videos, and sound" },
  { id: "104", title: "Financial administration" },
  { id: "105", title: "Financial services" },
  { id: "106", title: "Funds and trusts" },
  { id: "107", title: "Fundraising" },
  { id: "108", title: "Photography" },
  { id: "109", title: "Fruit and vegetable canning production" },
  { id: "110", title: "Mental healthcare" },
  { id: "111", title: "Fabricated metal products" },
  { id: "112", title: "Data infrastructure and analysis" },
  { id: "113", title: "Sound recording" },
  { id: "114", title: "Medicine" },
  { id: "115", title: "Health services" },
  { id: "116", title: "Gambling halls and casinos" },
  { id: "117", title: "Golf courses and country clubs" },
  { id: "118", title: "Graphic design" },
  { id: "119", title: "Wholesale" },
  { id: "120", title: "Wholesale alcoholic beverages" },
  { id: "121", title: "Wholesale equipment, electricity, and electronics" },
  { id: "122", title: "Wholesale building materials" },
  { id: "123", title: "Wholesale chemical and related products" },
  { id: "124", title: "Wholesale computer equipment" },
  { id: "125", title: "Wholesale photography equipment and products" },
  { id: "126", title: "Wholesale hardware, piping, heating equipment" },
  { id: "127", title: "Wholesale import and export" },
  { id: "128", title: "Wholesale machinery" },
  { id: "129", title: "Wholesale drugs and health products" },
  { id: "130", title: "Wholesale paper products" },
  { id: "131", title: "Wholesale shoes" },
  { id: "132", title: "Wholesale clothing and sewing supplies" },
  { id: "133", title: "Wholesale agricultural products" },
  { id: "134", title: "Wholesale food and beverage" },
  { id: "135", title: "Wholesale luxury goods and jewelry" },
  { id: "136", title: "Wholesale metals and minerals" },
  { id: "137", title: "Wholesale petroleum and petroleum products" },
  { id: "138", title: "Wholesale recyclable materials" },
  { id: "139", title: "Historical sites" },
  { id: "140", title: "Higher education" },
  { id: "141", title: "Holding companies" },
  { id: "142", title: "Hospitality and tourism" },
  { id: "143", title: "Hotels and motels" },
  { id: "144", title: "Pet services" },
  { id: "145", title: "Household services" },
  { id: "146", title: "Housing and community development" },
  { id: "147", title: "Housing programs" },
  { id: "148", title: "ICT and design services" },
  { id: "149", title: "Custom software development" },
  { id: "150", title: "ICT services and consultancy" },
  { id: "151", title: "ICT system testing and evaluation" },
  { id: "152", title: "ICT system training and support" },
  { id: "153", title: "Collection services" },
  { id: "154", title: "Internet media" },
  { id: "155", title: "Information services" },
  { id: "156", title: "Installation and removal of ICT systems" },
  { id: "157", title: "Interior design" },
  { id: "158", title: "International relations and diplomatic service" },
  { id: "159", title: "International trade and development" },
  { id: "160", title: "Internet news" },
  { id: "161", title: "Interurban and suburban bus transit" },
  { id: "162", title: "Investment advice" },
  { id: "163", title: "Investment banking" },
  { id: "164", title: "Cable and satellite programs" },
  { id: "165", title: "Office management" },
  { id: "166", title: "Capital markets" },
  { id: "167", title: "Daycare centers" },
  { id: "168", title: "Customer service" },
  { id: "169", title: "Clothing industry" },
  { id: "170", title: "Newspaper industry" },
  { id: "171", title: "Credit mediation" },
  { id: "172", title: "Credit brokers" },
  { id: "173", title: "Armed forces" },
  { id: "174", title: "Art academy" },
  { id: "175", title: "Artists and writers" },
  { id: "176", title: "Art dealers (retail)" },
  { id: "177", title: "Paint, coating, and adhesive manufacturing" },
  { id: "178", title: "Agriculture" },
  { id: "179", title: "Agriculture, forestry, fishing" },
  { id: "180", title: "Commercial real estate leasing" },
  { id: "181", title: "Residential real estate leasing" },
  { id: "182", title: "Leather goods manufacturing" },
  { id: "183", title: "Food and beverage industry" },
  { id: "184", title: "Airlines and aviation" },
  { id: "185", title: "Social development and urban planning" },
  { id: "186", title: "Machinery manufacturing" },
  { id: "187", title: "Real estate brokers" },
  { id: "188", title: "Marketing services" },
  { id: "189", title: "Market research" },
  { id: "190", title: "Media and telecommunications" },
  { id: "191", title: "Media production" },
  { id: "192", title: "Medical and research laboratories" },
  { id: "193", title: "Metalworking" },
  { id: "194", title: "Metal mining" },
  { id: "195", title: "Metal valve, shaft, and rail production" },
  { id: "196", title: "Furniture upholstery and repair" },
  { id: "197", title: "Mining" },
  { id: "198", title: "Non-metallic mineral mining" },
  { id: "199", title: "Mining, oil and gas extraction" },
  { id: "200", title: "Environmental protection programs" },
  { id: "201", title: "Environmental services" },
  { id: "202", title: "Environmental programs" },
  { id: "203", title: "Military and international relations" },
  { id: "204", title: "Mobile gaming apps" },
  { id: "205", title: "Mobile food services" },
  { id: "206", title: "Museums, historical sites, and zoos" },
  { id: "207", title: "Musicians" },
  { id: "208", title: "Management support" },
  { id: "209", title: "Nanotechnological research" },
  { id: "210", title: "Non-residential construction" },
  { id: "211", title: "Non-profit organizations" },
  { id: "212", title: "Emergency and other emergency services" },
  { id: "213", title: "Utilities" },
  { id: "214", title: "Natural resource management" },
  { id: "215", title: "Oil and gas extraction" },
  { id: "216", title: "Oil and coal production" },
  { id: "217", title: "Oil drilling" },
  { id: "218", title: "Broadcasting and distribution" },
  { id: "219", title: "Commercial and industrial equipment maintenance" },
  { id: "220", title: "Maintenance of electronic or precision equipment" },
  { id: "221", title: "Education" },
  { id: "222", title: "Research services" },
  { id: "223", title: "Online audio and video media" },
  { id: "224", title: "Public administration offices" },
  { id: "225", title: "Public safety" },
  { id: "226", title: "Operations consulting" },
  { id: "227", title: "Optometrists" },
  { id: "228", title: "Biomass generation" },
  { id: "229", title: "Fossil fuel generation" },
  { id: "230", title: "Geothermal energy generation" },
  { id: "231", title: "Nuclear energy generation" },
  { id: "232", title: "Wind energy generation" },
  { id: "233", title: "Solar energy generation" },
  { id: "234", title: "Paper and forestry" },
  { id: "235", title: "Prisons" },
  { id: "236", title: "Pension funds" },
  { id: "237", title: "Personal and laundry services" },
  { id: "238", title: "Pipeline transportation" },
  { id: "239", title: "Internet marketplace platforms" },
  { id: "240", title: "Performing arts" },
  { id: "241", title: "Outpatient care centers" },
  { id: "242", title: "Police and justice" },
  { id: "243", title: "Political organizations" },
  { id: "244", title: "Postal services" },
  { id: "245", title: "Amusement parks and arcades" },
  { id: "246", title: "Primary metal production" },
  { id: "247", title: "Automation machinery manufacturing" },
  { id: "248", title: "Tableware and hand tool manufacturing" },
  { id: "249", title: "Chemical raw material production" },
  { id: "250", title: "Communication equipment manufacturing" },
  { id: "251", title: "Defense and aerospace manufacturing" },
  { id: "252", title: "Electrical appliance manufacturing" },
  { id: "253", title: "Semiconductor lighting manufacturing" },
  { id: "254", title: "Glass, ceramic, and concrete manufacturing" },
  { id: "255", title: "Semiconductor manufacturing" },
  { id: "256", title: "Semiconductor manufacturing for sustainable energy" },
  { id: "257", title: "Household appliance manufacturing" },
  {
    id: "258",
    title: "Household appliance and consumer electronics manufacturing",
  },
  { id: "259", title: "Industrial machinery manufacturing" },
  { id: "260", title: "Artificial rubber and synthetic fiber manufacturing" },
  { id: "261", title: "Magnetic and optical media manufacturing" },
  { id: "262", title: "Mattress and blinds manufacturing" },
  { id: "263", title: "Medical equipment manufacturing" },
  { id: "264", title: "Metalworking machinery manufacturing" },
  { id: "265", title: "Motor vehicle parts manufacturing" },
  { id: "266", title: "Motor vehicle manufacturing" },
  { id: "267", title: "Plastic and rubber manufacturing" },
  { id: "268", title: "Personal care and hygiene product manufacturing" },
  { id: "269", title: "Abrasives and non-metallic mineral manufacturing" },
  { id: "270", title: "Renewable energy equipment manufacturing" },
  { id: "271", title: "Computer and electronic device manufacturing" },
  { id: "272", title: "Clay and refractory product manufacturing" },
  {
    id: "273",
    title: "Commercial and service industry machinery manufacturing",
  },
  { id: "274", title: "Measuring and control equipment manufacturing" },
  { id: "275", title: "Office furniture and equipment manufacturing" },
  { id: "276", title: "Residential furniture and furnishings manufacturing" },
  { id: "277", title: "Fashion accessories manufacturing" },
  { id: "278", title: "Aerospace and motor vehicle parts manufacturing" },
  { id: "279", title: "Sports and fitness equipment manufacturing" },
  { id: "280", title: "Packaging and container manufacturing" },
  { id: "281", title: "Video and audio equipment manufacturing" },
  { id: "282", title: "Soap and cleaning agent manufacturing" },
  { id: "283", title: "Dairy product manufacturing" },
  { id: "284", title: "Heating and cooling equipment manufacturing" },
  { id: "285", title: "Professional organizations" },
  { id: "286", title: "Professional services" },
  { id: "287", title: "Professional training and coaching" },
  { id: "288", title: "Air, water, and waste program management" },
  { id: "289", title: "Public relations and communication services" },
  { id: "290", title: "Public services" },
  { id: "291", title: "Program management" },
  { id: "292", title: "Racetracks" },
  { id: "293", title: "Radio and TV broadcasts" },
  { id: "294", title: "Courts" },
  { id: "295", title: "Advertising and advertisers services" },
  { id: "296", title: "Recreation facilities" },
  { id: "297", title: "Travel industry" },
  { id: "298", title: "Religious institutions" },
  { id: "299", title: "Repair and maintenance" },
  { id: "300", title: "Residential construction" },
  { id: "301", title: "Restaurants" },
  { id: "302", title: "Aerospace research and technology" },
  { id: "303", title: "Compensation claims and actuarial services" },
  { id: "304", title: "Shipbuilding" },
  { id: "305", title: "Shoe and leather goods repair" },
  { id: "306", title: "Shoe manufacturing" },
  { id: "307", title: "School and employee bus services" },
  { id: "308", title: "Cleaning services" },
  { id: "309", title: "Writing and editing" },
  { id: "310", title: "Secretary training" },
  { id: "311", title: "Strategic management services" },
  { id: "312", title: "Renewable energy services" },
  { id: "313", title: "Shuttles and specialized transport services" },
  { id: "314", title: "Ski facilities" },
  { id: "315", title: "Social network platforms" },
  { id: "316", title: "Software development" },
  { id: "317", title: "Data security software products" },
  { id: "318", title: "Desktop software products" },
  { id: "319", title: "Mobile computer software products" },
  { id: "320", title: "Savings institutions" },
  { id: "321", title: "Railway transportation" },
  { id: "322", title: "Sports and recreation lessons" },
  { id: "323", title: "Sports teams and clubs" },
  { id: "324", title: "City transportation services" },
  { id: "325", title: "Coal mining" },
  { id: "326", title: "Vocational education student" },
  { id: "327", title: "Undergraduate student" },
  { id: "328", title: "Graduate student" },
  { id: "329", title: "Language schools" },
  { id: "330", title: "Tobacco production" },
  { id: "331", title: "Dentists" },
  { id: "332", title: "Taxi and limousine services" },
  { id: "333", title: "Technical services" },
  { id: "334", title: "Technical and vocational training" },
  { id: "335", title: "Technology, information, and media" },
  { id: "336", title: "Telecommunication providers" },
  { id: "337", title: "Telecommunications" },
  { id: "338", title: "Satellite telecommunications" },
  { id: "339", title: "Textile manufacturing" },
  { id: "340", title: "Theater companies" },
  { id: "341", title: "Home care" },
  { id: "342", title: "Temporary aid services" },
  { id: "343", title: "Magazine industry" },
  { id: "344", title: "Tourist transportation" },
  { id: "345", title: "Transport, logistics, supply chain, and storage" },
  { id: "346", title: "Trusts and estates" },
  { id: "347", title: "Horticulture" },
  { id: "348", title: "Book and magazine publishers" },
  { id: "349", title: "Sheet music publishers" },
  { id: "350", title: "Executive authorities" },
  { id: "351", title: "Performing arts and spectator sports" },
  { id: "352", title: "Livestock farming" },
  { id: "353", title: "Livestock and fisheries" },
  { id: "354", title: "Consumer goods rental" },
  { id: "355", title: "Commercial and industrial equipment rental" },
  { id: "356", title: "Equipment rental services" },
  { id: "357", title: "Nursing homes and assisted living facilities" },
  { id: "358", title: "Translations and localization" },
  { id: "359", title: "Transportation programs" },
  { id: "360", title: "Insurers" },
  { id: "361", title: "Insurance" },
  { id: "362", title: "Insurance and secondary personnel benefits" },
  { id: "363", title: "Insurance companies and intermediaries" },
  { id: "364", title: "Fish products" },
  { id: "365", title: "Fisheries" },
  { id: "366", title: "Flight training" },
  { id: "367", title: "Vehicle repair and maintenance" },
  { id: "368", title: "Public health" },
  { id: "369", title: "Steam and air conditioning supply" },
  { id: "370", title: "Freight and parcel transportation" },
  { id: "371", title: "Truck transportation" },
  { id: "372", title: "Department stores and storage" },
  { id: "373", title: "Laundromats and dry cleaners" },
  { id: "374", title: "Water supply and irrigation systems" },
  { id: "375", title: "Road, street, and bridge construction" },
  { id: "376", title: "Wellness and fitness services" },
  { id: "377", title: "Operation and maintenance of IT systems" },
  { id: "378", title: "Legislative authorities" },
  { id: "379", title: "Wineries" },
  { id: "380", title: "Web & App design" },
  { id: "381", title: "Marine transportation" },
  { id: "382", title: "Hospitals" },
  { id: "383", title: "Hospitals and healthcare" },
  { id: "384", title: "Executive search services" },
];

export let languages: any = [
  { id: 1, title: "Dutch" },
  { id: 2, title: "English" },
  { id: 3, title: "German" },
  { id: 4, title: "French" },
  { id: 5, title: "Spanish" },
  { id: 6, title: "Arabic" },
  { id: 7, title: "Turkish" },
  { id: 8, title: "Berber (Tamazight)" },
  { id: 9, title: "Polish" },
  { id: 10, title: "Papiamento" },
  { id: 11, title: "Portuguese" },
  { id: 12, title: "Chinese (Mandarin and Cantonese)" },
  { id: 13, title: "Italian" },
  { id: 14, title: "Russian" },
  { id: 15, title: "Romanian" },
  { id: 16, title: "Bulgarian" },
  { id: 17, title: "Somali" },
  { id: 18, title: "Hindi" },
  { id: 19, title: "Urdu" },
  { id: 20, title: "Vietnamese" },
  { id: 21, title: "Greek" },
  { id: 22, title: "Tigrinya" },
  { id: 23, title: "Japanese" },
  { id: 24, title: "Kurdish" },
  { id: 25, title: "Indonesian" }
];
